import { Link } from "react-router-dom";
import { motion } from "motion/react";

export function LandingPage() {
  return (
    <div className="w-full max-w-[900px] px-6 mx-auto pt-20 pb-32 text-center text-[var(--star)] relative z-10" style={{fontFamily: "'DM Mono', monospace"}}>
      
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
      >
        <p className="eyebrow mb-4 tracking-[0.4em] text-[10px]">Welcome to the Beyond</p>
        <h1 className="display text-6xl leading-[1.1] mb-8 font-light max-w-2xl mx-auto">
          The <em className="text-[var(--gold-l)]">Career</em> Oracle
        </h1>
        <p className="text-sm md:text-base leading-relaxed text-[var(--mist)] max-w-2xl mx-auto mb-6">
          A career discovery tool grounded in real psychology — Big Five
          personality, Holland Code (RIASEC) vocational interests, and
          decision-making style — scored with plain, deterministic math and
          matched against real occupational profiles.
        </p>
        <div className="glass max-w-xl mx-auto mb-12 text-left px-6 py-5">
          <p className="text-[13px] leading-relaxed text-[rgba(240,234,255,0.7)]">
            <span className="text-[var(--gold-l)]">A snapshot, not a verdict:</span>{" "}
            what you get is a picture of how you think and what interests you{" "}
            <em>today</em>. Your thinking evolves as you learn and grow, so
            treat this as a starting point for exploration — not a fixed
            label on who you are.
          </p>
        </div>
        
        <Link to="/app">
          <button className="btn btn-primary text-[12px] px-8 py-4 mb-24">
            <span>Enter The Oracle ✦</span>
          </button>
        </Link>
      </motion.div>

      <div className="orn w-full max-w-sm mx-auto mb-24">
        <div className="orn-l" />
        <span className="orn-c text-2xl">◎</span>
        <div className="orn-r" />
      </div>

      <motion.div
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 1 }}
        className="text-left leading-relaxed text-[var(--star)] max-w-3xl mx-auto space-y-8 font-cg text-lg md:text-xl"
      >
        <h2 className="display text-4xl mb-6 text-center text-[var(--gold)]">The Science Behind the Oracle</h2>
        <p>
          Career guidance is usually one of two things: a vague personality quiz that tells you what you want to hear, or an AI chatbot that invents a percentage match out of thin air. The Career Oracle takes a different approach. Every diagnostic score you receive is computed with plain, transparent arithmetic from validated psychological constructs — nothing is fabricated, guessed, or generated by a language model.
        </p>

        <p>
          The assessment draws on five well-established, published frameworks. The <strong>Big Five</strong> model of personality (openness, conscientiousness, extraversion, agreeableness, emotional stability) is the most replicated framework in personality psychology. <strong>Holland's RIASEC model</strong> — the same vocational-interest framework behind O*NET's Interest Profiler used by professional career counselors — maps your interests across six domains: Realistic, Investigative, Artistic, Social, Enterprising, and Conventional. A short set of <strong>cognitive reflection puzzles</strong> (from Shane Frederick's 2005 research) objectively measures whether you lean analytical or intuitive, since these are scored as right or wrong, not self-reported. And two well-studied decision-making traits — <strong>risk tolerance</strong> and <strong>locus of control</strong> — round out the picture, alongside Kirton's adaptor–innovator theory of problem-solving style.
        </p>

        <h3 className="display text-3xl mt-12 mb-6 text-center text-[var(--gold)]">Deterministic Scoring, Not AI Guessing</h3>

        <p>
          Once you answer the questions, your responses are converted into trait scores using fixed formulas — the same answers will always produce the same scores, every time, for anyone. Your trait profile is then compared against a curated reference set of occupations, each classified with its own Holland Code and personality profile drawn from published occupational psychology descriptions. The comparison is plain vector math: a weighted distance calculation across your interests, personality, risk tolerance, and problem-solving style. No AI model is involved in scoring your assessment or ranking your career matches — the process is fully auditable and repeatable.
        </p>

        <p>
          Where AI genuinely helps is a different job entirely: once you've seen your matches, you can ask for tailored book recommendations, topics to study, and resources to help you grow toward a career you're curious about. That's a generative, exploratory task well-suited to AI — very different from the diagnostic scoring, which stays deterministic.
        </p>

        <h3 className="display text-3xl mt-12 mb-6 text-center text-[var(--gold)]">A Snapshot, Not a Fixed Verdict</h3>

        <p>
          Here is the honest caveat that most career tools leave out: personality traits, interests, and thinking styles are not permanently fixed. Decades of longitudinal research show that traits like conscientiousness and emotional stability shift meaningfully across a lifetime, and interests can deepen or change entirely as you gain new experiences and knowledge. What this assessment measures is real — but it's a snapshot of how you think and what draws your interest <em>right now</em>, not an immutable label.
        </p>

        <p>
          That's precisely why the growth-suggestions step exists. The point isn't to hand you a verdict and walk away — it's to give you a grounded starting point, plus a concrete path to keep learning, testing your interests against reality, and revisiting the assessment as your thinking evolves.
        </p>

        <h3 className="display text-3xl mt-12 mb-6 text-center text-[var(--gold)]">What to Expect</h3>

        <p>
          You'll work through a short series of question sets covering personality, vocational interests, a couple of logic puzzles, your problem-solving style, and your appetite for risk. Your results show your Big Five profile, your RIASEC interest breakdown, your thinking-style descriptors, and a ranked list of career matches with plain-language explanations of why each one overlaps with your profile. From there, you can explore AI-generated growth suggestions — books, topics, and resources — for any career that catches your interest.
        </p>
      </motion.div>

      <div className="orn w-full max-w-sm mx-auto mt-24 mb-16">
        <div className="orn-l" />
        <span className="orn-c text-2xl">◎</span>
        <div className="orn-r" />
      </div>

      <Link to="/app">
        <button className="btn btn-primary text-[14px] px-10 py-5">
          <span>Begin The Assessment ✦</span>
        </button>
      </Link>

    </div>
  );
}
